### PR TITLE
feat: Support operationId property

### PR DESCRIPTION
**Pull request by fedorov-xyz**

### CODE REVIEW

**Comment by fedorov-xyz** [comment]
@ShogunPanda hey! Could you please review?

**Review by ShogunPanda — CHANGES_REQUESTED** [review]
Hello! Please remove the changes in `.gitignore`, rest LGTM.

**Comment by fedorov-xyz** [comment]
Sure, I can do that. But what's the reason? When I install dependecies locally, both node_modules and lock file are highlighted as untracked files

image

**Comment by fedorov-xyz** [comment]
Done. Also fixed failed pipeline

**Comment by ShogunPanda** [comment]
> Sure, I can do that. But what's the reason? When I install dependecies locally, both node_modules and lock file are highlighted as untracked files
> 
> image

I have it in my global `.gitignore_global`.

**Comment by fedorov-xyz** [comment]
Yeah, makes sense. In general it is good practice to locally host ignores, since third-party contributors may also work with the repository. Also, the repository should have a lock file with package versions, so that all contributors and CI have consistent behavior. What do you think?

**Comment by ShogunPanda** [comment]
I don't like to submit lockfile as they add a lot of problems when rebasing branches. I rely on semver adoption from packages maintainers.

**Pull request merged**
